/*
 * ACHFileControlDialog.java
 *
 * Created on April 16, 2007, 7:45 PM
 */

package com.ach.achViewer;

import com.ach.achViewer.ach.ACHRecord;
import com.ach.achViewer.ach.ACHRecordBatchControl;

/**
 * 
 * @author John
 */
public class ACHBatchControlDialog extends ACHDialog {

	static final long serialVersionUID = 0;

	public static final int SAVE_BUTTON = 1;

	public static final int CANCEL_BUTTON = 2;

	private int buttonSelected = CANCEL_BUTTON;

	private ACHRecordBatchControl achRecord = null;

	/** Creates new form ACHFileControlDialog */
	public ACHBatchControlDialog(java.awt.Frame parent, boolean modal,
			ACHRecordBatchControl achRecord) {
		super(parent, modal);
		initComponents();

		setAchRecord(achRecord);

		getRootPane().setDefaultButton(jButtonSave); // Sets the Save
		// button to default
		setLocationRelativeTo(null); // Centers the window on the screen
		loadDialogValues();
	}

	private void loadDialogValues() {
		jTextFieldRecordTypeCode.setText(String.valueOf(achRecord
				.getRecordTypeCode()));
		jTextFieldServiceClassCode.setText(achRecord.getServiceClassCode());
		jTextFieldEntryAddendaCount.setText(achRecord.getEntryAddendaCount());
		jTextFieldEntryHash.setText(achRecord.getEntryHash());
		jTextFieldTotDebitDollarAmt.setText(achRecord.getTotDebitDollarAmt());
		jTextFieldTotCreditDollarAmt.setText(achRecord.getTotCreditDollarAmt());
		jTextFieldCompanyID.setText(achRecord.getCompanyId());
		jTextFieldMessageAuthenticationCode.setText(achRecord
				.getMessageAuthCode());
		jTextFieldReserved.setText(achRecord.getReserved());
		jTextFieldOriginatingDFIID.setText(achRecord.getOriginatingDfiId());
		jTextFieldBatchNumber.setText(achRecord.getBatchNumber());
	}

	private void retrieveDialogValues() {
		achRecord.setRecordTypeCode(ACHRecord.BATCH_CONTROL_TYPE);
		achRecord.setServiceClassCode(jTextFieldServiceClassCode.getText());
		achRecord.setEntryAddendaCount(jTextFieldEntryAddendaCount.getText());
		achRecord.setEntryHash(jTextFieldEntryHash.getText());
		achRecord.setTotDebitDollarAmt(jTextFieldTotDebitDollarAmt.getText());
		achRecord.setTotCreditDollarAmt(jTextFieldTotCreditDollarAmt.getText());
		achRecord.setCompanyId(jTextFieldCompanyID.getText());
		achRecord.setMessageAuthCode(jTextFieldMessageAuthenticationCode
				.getText());
		achRecord.setReserved(jTextFieldReserved.getText());
		achRecord.setOriginatingDfiId(jTextFieldOriginatingDFIID.getText());
		achRecord.setBatchNumber(jTextFieldBatchNumber.getText());
	}

	/**
	 * @return the achRecord
	 */
	public synchronized ACHRecordBatchControl getAchRecord() {
		return achRecord;
	}

	/**
	 * @param achRecord
	 *            the achRecord to set
	 */
	private synchronized void setAchRecord(ACHRecordBatchControl achRecord) {
		this.achRecord = achRecord;
	}

	/**
	 * @return the buttonSelected
	 */
	public synchronized int getButtonSelected() {
		return buttonSelected;
	}

	/**
	 * @param buttonSelected
	 *            the buttonSelected to set
	 */
	public synchronized void setButtonSelected(int buttonSelected) {
		this.buttonSelected = buttonSelected;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelBatchHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRecordTypeCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldServiceClassCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBatchNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEntryAddendaCount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEntryHash = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTotDebitDollarAmt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTotCreditDollarAmt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCompanyID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldMessageAuthenticationCode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldReserved = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldOriginatingDFIID = new javax.swing.JTextField();
        jPanelButtons = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ACH Batch Control");
        setModal(true);
        jLabel1.setText("Record Type: ");

        jTextFieldRecordTypeCode.setEditable(false);
        jTextFieldRecordTypeCode.setText("8");
        jTextFieldRecordTypeCode.setToolTipText("Must be 8");
        jTextFieldRecordTypeCode.setFocusable(false);
        jTextFieldRecordTypeCode.setName("Record Type");

        jLabel2.setText("Service Class Code:");

        jTextFieldServiceClassCode.setText("123");
        jTextFieldServiceClassCode.setToolTipText("");
        jTextFieldServiceClassCode.setInputVerifier(new NumericVerifier(0,999));
        jTextFieldServiceClassCode.setName("Service Class Code");

        jLabel3.setText("Batch Number:");

        jTextFieldBatchNumber.setText("1234567");
        jTextFieldBatchNumber.setToolTipText("");
        jTextFieldBatchNumber.setInputVerifier(new NumericVerifier(1,9999999L));
        jTextFieldBatchNumber.setName("Batch Number");

        jLabel4.setText("Entry/Addenda Count:");

        jTextFieldEntryAddendaCount.setText("123456");
        jTextFieldEntryAddendaCount.setToolTipText("");
        jTextFieldEntryAddendaCount.setInputVerifier(new NumericVerifier(0,999999));
        jTextFieldEntryAddendaCount.setName("Entry/Addenda Count");

        jLabel5.setText("Entry Hash:");

        jTextFieldEntryHash.setText("1234567890");
        jTextFieldEntryHash.setToolTipText("");
        jTextFieldEntryHash.setInputVerifier(new NumericVerifier(0,9999999999L));
        jTextFieldEntryHash.setName("Entry Hash");

        jLabel6.setText("Total Debit Entry Amount:");

        jTextFieldTotDebitDollarAmt.setText("123456789012");
        jTextFieldTotDebitDollarAmt.setToolTipText("");
        jTextFieldTotDebitDollarAmt.setInputVerifier(new NumericVerifier(0,999999999999L));
        jTextFieldTotDebitDollarAmt.setName("Total Debit Entry Dollar Amount");

        jLabel7.setText("Total Credit Entry Amount:");

        jTextFieldTotCreditDollarAmt.setText("123456789012");
        jTextFieldTotCreditDollarAmt.setToolTipText("");
        jTextFieldTotCreditDollarAmt.setInputVerifier(new NumericVerifier(0,999999999999L));
        jTextFieldTotCreditDollarAmt.setName("Total Credit Entry Dollar Amount");

        jLabel8.setText("Company Identification:");

        jTextFieldCompanyID.setText("ABCDEFGHIJ");
        jTextFieldCompanyID.setToolTipText("");
        jTextFieldCompanyID.setInputVerifier(new StringVerifier(1,10));
        jTextFieldCompanyID.setName("Company Identification");

        jLabel9.setText("Message Authentication Code:");

        jTextFieldMessageAuthenticationCode.setText("ABCDEFGHIJKLMNOPQRS");
        jTextFieldMessageAuthenticationCode.setToolTipText("");
        jTextFieldMessageAuthenticationCode.setInputVerifier(new StringVerifier(0,19));
        jTextFieldMessageAuthenticationCode.setName("TotalMessage Authentication Code");

        jLabel10.setText("Reserved:");

        jTextFieldReserved.setEditable(false);
        jTextFieldReserved.setText("      ");
        jTextFieldReserved.setToolTipText("");
        jTextFieldReserved.setFocusable(false);
        jTextFieldReserved.setInputVerifier(new StringVerifier(0,6));
        jTextFieldReserved.setName("Reserved");

        jLabel11.setText("Originating DFI Identification:");

        jTextFieldOriginatingDFIID.setText("ABCDEFGHIJKLMNOPQRS");
        jTextFieldOriginatingDFIID.setToolTipText("");
        jTextFieldOriginatingDFIID.setInputVerifier(new StringVerifier(8,8));
        jTextFieldOriginatingDFIID.setName("Originating DFI Identification");

        javax.swing.GroupLayout jPanelBatchHeaderLayout = new javax.swing.GroupLayout(jPanelBatchHeader);
        jPanelBatchHeader.setLayout(jPanelBatchHeaderLayout);
        jPanelBatchHeaderLayout.setHorizontalGroup(
            jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBatchHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBatchNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jTextFieldOriginatingDFIID, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldReserved, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMessageAuthenticationCode, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotCreditDollarAmt, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jTextFieldTotDebitDollarAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEntryHash, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jTextFieldEntryAddendaCount, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jTextFieldServiceClassCode, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jTextFieldRecordTypeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelBatchHeaderLayout.setVerticalGroup(
            jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBatchHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRecordTypeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldServiceClassCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEntryAddendaCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEntryHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTotDebitDollarAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTotCreditDollarAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMessageAuthenticationCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldReserved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOriginatingDFIID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBatchNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonSave)
                .addComponent(jButtonCancel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBatchHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBatchHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCancelActionPerformed
		dispose();
	}// GEN-LAST:event_jButtonCancelActionPerformed

	private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSaveActionPerformed
		retrieveDialogValues();
		setButtonSelected(SAVE_BUTTON);
		dispose();
	}// GEN-LAST:event_jButtonSaveActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ACHBatchControlDialog(new javax.swing.JFrame(), true,
						new ACHRecordBatchControl()).setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelBatchHeader;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JTextField jTextFieldBatchNumber;
    private javax.swing.JTextField jTextFieldCompanyID;
    private javax.swing.JTextField jTextFieldEntryAddendaCount;
    private javax.swing.JTextField jTextFieldEntryHash;
    private javax.swing.JTextField jTextFieldMessageAuthenticationCode;
    private javax.swing.JTextField jTextFieldOriginatingDFIID;
    private javax.swing.JTextField jTextFieldRecordTypeCode;
    private javax.swing.JTextField jTextFieldReserved;
    private javax.swing.JTextField jTextFieldServiceClassCode;
    private javax.swing.JTextField jTextFieldTotCreditDollarAmt;
    private javax.swing.JTextField jTextFieldTotDebitDollarAmt;
    // End of variables declaration//GEN-END:variables

}
