/*
 * ACHFileControlDialog.java
 *
 * Created on April 16, 2007, 7:45 PM
 */

package com.ach.achViewer;

import com.ach.achViewer.ach.ACHRecord;
import com.ach.achViewer.ach.ACHRecordFileHeader;

/**
 * 
 * @author John
 */
public class ACHFileHeaderDialog extends ACHDialog {

	static final long serialVersionUID = 0;
	
	public static final int SAVE_BUTTON = 1;

	public static final int CANCEL_BUTTON = 2;

	private int buttonSelected = CANCEL_BUTTON;

	private ACHRecordFileHeader achRecord = null;

	/** Creates new form ACHFileControlDialog */
	public ACHFileHeaderDialog(java.awt.Frame parent, boolean modal,
			ACHRecordFileHeader achRecord) {
		super(parent, modal);
		initComponents();

		setAchRecord(achRecord);

		getRootPane().setDefaultButton(jButtonSave); // Sets the Save
		// button to default
		setLocationRelativeTo(null); // Centers the window on the screen
		loadDialogValues();
	}

	private void loadDialogValues() {
		jTextFieldRecordTypeCode.setText(String.valueOf(achRecord
				.getRecordTypeCode()));
		jTextFieldPriorityCode.setText(achRecord.getPriorityCode());
		jTextFieldImmDestination.setText(achRecord.getImmediateDestination());
		jTextFieldImmOrigin.setText(achRecord.getImmediateOrigin());
		jTextFieldFileCreationDate.setText(achRecord.getFileCreationDate());
		jTextFieldFileCreationTime.setText(achRecord.getFileCreationTime());
		jTextFieldFileIDModifier.setText(achRecord.getFileIdModifier());
		jTextFieldRecordSize.setText(achRecord.getRecordSize());
		jTextFieldBlockingFactor.setText(achRecord.getBlockingFactor());
		jTextFieldFormatCode.setText(achRecord.getFormatCode());
		jTextFieldImmDestName.setText(achRecord.getImmediateDestinationName());
		jTextFieldImmOriginName.setText(achRecord.getImmediateOriginName());
		jTextFieldReferenceCode.setText(achRecord.getReferenceCode());
	}
	
	private void retrieveDialogValues() {
		achRecord.setRecordTypeCode(ACHRecord.FILE_HEADER_TYPE);
		achRecord.setPriorityCode(jTextFieldPriorityCode.getText());
		achRecord.setImmediateDestination(jTextFieldImmDestination.getText());
		achRecord.setImmediateOrigin(jTextFieldImmOrigin.getText());
		achRecord.setFileCreationDate(jTextFieldFileCreationDate.getText());
		achRecord.setFileCreationTime(jTextFieldFileCreationTime.getText());
		achRecord.setFileIdModifier(jTextFieldFileIDModifier.getText());
		achRecord.setRecordSize(jTextFieldRecordSize.getText());
		achRecord.setBlockingFactor(jTextFieldBlockingFactor.getText());
		achRecord.setFormatCode(jTextFieldFormatCode.getText());
		achRecord.setImmediateDestinationName(jTextFieldImmDestName.getText());
		achRecord.setImmediateOriginName(jTextFieldImmOriginName.getText());
		achRecord.setReferenceCode(jTextFieldReferenceCode.getText());
	}

	/**
	 * @return the achRecord
	 */
	public synchronized ACHRecordFileHeader getAchRecord() {
		return achRecord;
	}

	/**
	 * @param achRecord
	 *            the achRecord to set
	 */
	private synchronized void setAchRecord(ACHRecordFileHeader achRecord) {
		this.achRecord = achRecord;
	}

	/**
	 * @return the buttonSelected
	 */
	public synchronized int getButtonSelected() {
		return buttonSelected;
	}

	/**
	 * @param buttonSelected
	 *            the buttonSelected to set
	 */
	public synchronized void setButtonSelected(int buttonSelected) {
		this.buttonSelected = buttonSelected;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelFileControl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRecordTypeCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPriorityCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldImmDestination = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldImmOrigin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFileCreationDate = new javax.swing.JTextField();
        jTextFieldFileCreationTime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldFileIDModifier = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldRecordSize = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldBlockingFactor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldFormatCode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldImmDestName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldImmOriginName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldReferenceCode = new javax.swing.JTextField();
        jPanelButtons = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ACH File Header");
        jLabel1.setText("Record Type: ");

        jTextFieldRecordTypeCode.setEditable(false);
        jTextFieldRecordTypeCode.setText("1");
        jTextFieldRecordTypeCode.setToolTipText("Must be 1");
        jTextFieldRecordTypeCode.setFocusable(false);
        jTextFieldRecordTypeCode.setName("Record Type");

        jLabel2.setText("Priority Code:");

        jTextFieldPriorityCode.setEditable(false);
        jTextFieldPriorityCode.setText("01");
        jTextFieldPriorityCode.setInputVerifier(new NumericVerifier(0,99));
        jTextFieldPriorityCode.setName("Priority Code");

        jLabel3.setText("Immediate Destination:");

        jTextFieldImmDestination.setText("bTTTTAAAAC");
        jTextFieldImmDestination.setInputVerifier(new StringVerifier(10,10));
        jTextFieldImmDestination.setName("Immediate Destination");

        jLabel4.setText("Immediate Origin:");

        jTextFieldImmOrigin.setText("bTTTTAAAAC");
        jTextFieldImmOrigin.setInputVerifier(new StringVerifier(10,10));
        jTextFieldImmOrigin.setName("Immediate Origin");

        jLabel5.setText("File CreationDate/Time:");

        jTextFieldFileCreationDate.setText("YYMMDD");
        jTextFieldFileCreationDate.setInputVerifier(new StringVerifier(6,6));
        jTextFieldFileCreationDate.setName("File Creation Date");

        jTextFieldFileCreationTime.setText("HHMM");
        jTextFieldFileCreationTime.setInputVerifier(new StringVerifier(0,4));
        jTextFieldFileCreationTime.setName("File Creation Time");

        jLabel6.setText("File ID Modifier:");

        jTextFieldFileIDModifier.setText("X");
        jTextFieldFileIDModifier.setInputVerifier(new StringVerifier(1,1));
        jTextFieldFileIDModifier.setName("File ID Modifier");

        jLabel7.setText("Record Size:");

        jTextFieldRecordSize.setEditable(false);
        jTextFieldRecordSize.setText("94");
        jTextFieldRecordSize.setToolTipText("Must be 94");
        jTextFieldRecordSize.setFocusable(false);
        jTextFieldRecordSize.setInputVerifier(new NumericVerifier(94,94));
        jTextFieldRecordSize.setName("Record Size");

        jLabel8.setText("Blocking Factor:");

        jTextFieldBlockingFactor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldBlockingFactor.setText("10");
        jTextFieldBlockingFactor.setToolTipText("Must be between 1 and 10");
        jTextFieldBlockingFactor.setInputVerifier(new NumericVerifier(0,99));
        jTextFieldBlockingFactor.setName("Blocking Factor");

        jLabel9.setText("Format Code:");

        jTextFieldFormatCode.setEditable(false);
        jTextFieldFormatCode.setText("1");
        jTextFieldFormatCode.setFocusable(false);
        jTextFieldFormatCode.setInputVerifier(new NumericVerifier(1,9));
        jTextFieldFormatCode.setName("Format Code");

        jLabel10.setText("Immediate Destination Name:");

        jTextFieldImmDestName.setText("ABCDEFGHIJKLMNHOPQRSTUVW");
        jTextFieldImmDestName.setInputVerifier(new StringVerifier(0,23));
        jTextFieldImmDestName.setName("Immediate Destination Name");

        jLabel11.setText("Immediate Origin Name:");

        jTextFieldImmOriginName.setText("ABCDEFGHIJKLMNHOPQRSTUVW");
        jTextFieldImmOriginName.setInputVerifier(new StringVerifier(0,23));
        jTextFieldImmOriginName.setName("Immediate Origin Name");

        jLabel12.setText("Reference Code:");

        jTextFieldReferenceCode.setText("ABCDEFGH");
        jTextFieldReferenceCode.setInputVerifier(new StringVerifier(0,8));
        jTextFieldReferenceCode.setName("Reference Code");

        javax.swing.GroupLayout jPanelFileControlLayout = new javax.swing.GroupLayout(jPanelFileControl);
        jPanelFileControl.setLayout(jPanelFileControlLayout);
        jPanelFileControlLayout.setHorizontalGroup(
            jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFileControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldReferenceCode, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldImmOriginName)
                    .addComponent(jTextFieldImmDestName)
                    .addComponent(jTextFieldFormatCode, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jTextFieldBlockingFactor, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jTextFieldRecordSize, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jTextFieldFileIDModifier, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jTextFieldImmOrigin, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jTextFieldImmDestination, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jTextFieldPriorityCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRecordTypeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFileControlLayout.createSequentialGroup()
                        .addComponent(jTextFieldFileCreationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFileCreationTime, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelFileControlLayout.setVerticalGroup(
            jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFileControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRecordTypeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPriorityCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldImmDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldImmOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldFileCreationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFileCreationTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldFileIDModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldRecordSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldBlockingFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldFormatCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldImmDestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldImmOriginName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldReferenceCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonSave)
                .addComponent(jButtonCancel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelFileControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFileControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCancelActionPerformed
		dispose();
	}// GEN-LAST:event_jButtonCancelActionPerformed

	private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSaveActionPerformed
		retrieveDialogValues();
		setButtonSelected(SAVE_BUTTON);
		dispose();
	}// GEN-LAST:event_jButtonSaveActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ACHFileHeaderDialog(new javax.swing.JFrame(), true,
						new ACHRecordFileHeader()).setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelFileControl;
    private javax.swing.JTextField jTextFieldBlockingFactor;
    private javax.swing.JTextField jTextFieldFileCreationDate;
    private javax.swing.JTextField jTextFieldFileCreationTime;
    private javax.swing.JTextField jTextFieldFileIDModifier;
    private javax.swing.JTextField jTextFieldFormatCode;
    private javax.swing.JTextField jTextFieldImmDestName;
    private javax.swing.JTextField jTextFieldImmDestination;
    private javax.swing.JTextField jTextFieldImmOrigin;
    private javax.swing.JTextField jTextFieldImmOriginName;
    private javax.swing.JTextField jTextFieldPriorityCode;
    private javax.swing.JTextField jTextFieldRecordSize;
    private javax.swing.JTextField jTextFieldRecordTypeCode;
    private javax.swing.JTextField jTextFieldReferenceCode;
    // End of variables declaration//GEN-END:variables

}
