/*
 * ACHFileControlDialog.java
 *
 * Created on April 16, 2007, 7:45 PM
 */

package com.ach.achViewer;

import com.ach.achViewer.ach.ACHRecord;
import com.ach.achViewer.ach.ACHRecordBatchHeader;
import com.ach.achViewer.ach.ACHRecordFileHeader;

/**
 * 
 * @author John
 */
public class ACHBatchHeaderDialog extends ACHDialog {

	static final long serialVersionUID = 0;
	
	public static final int SAVE_BUTTON = 1;

	public static final int CANCEL_BUTTON = 2;

	private int buttonSelected = CANCEL_BUTTON;

	private ACHRecordBatchHeader achRecord = null;

	/** Creates new form ACHFileControlDialog */
	public ACHBatchHeaderDialog(java.awt.Frame parent, boolean modal,
			ACHRecordBatchHeader achRecord) {
		super(parent, modal);
		initComponents();

		setAchRecord(achRecord);

		getRootPane().setDefaultButton(jButtonSave); // Sets the Save
		// button to default
		setLocationRelativeTo(null); // Centers the window on the screen
		loadDialogValues();
	}

	private void loadDialogValues() {
		jTextFieldRecordTypeCode.setText(String.valueOf(achRecord
				.getRecordTypeCode()));
		jTextFieldServiceClassCode.setText(achRecord.getServiceClassCode());
		jTextFieldCompanyName.setText(achRecord.getCompanyName());
		jTextFieldCompanyDiscretionaryData.setText(achRecord.getCompanyDiscretionaryData());
		jTextFieldCompanyIdentification.setText(achRecord.getCompanyId());
		jTextFieldStandardEntryClassCode.setText(achRecord.getStandardEntryClassCode());
		jTextFieldCompanyEntryDescription.setText(achRecord.getCompanyEntryDescription());
		jTextFieldCompanyDescriptiveDate.setText(achRecord.getCompanyDescriptiveDate());
		jTextFieldEffectiveEntryDate.setText(achRecord.getEffectiveEntryDate());
		jTextFieldSettlementDate.setText(achRecord.getSettlementDate());
		jTextFieldOriginatorStatusCode.setText(achRecord.getOriginatorStatusCode());
		jTextFieldOriginatingDFIID.setText(achRecord.getOriginationDfiId());
		jTextFieldBatchNumber.setText(achRecord.getBatchNumber());
	}
	
	private void retrieveDialogValues() {
		achRecord.setRecordTypeCode(ACHRecord.BATCH_HEADER_TYPE);
		achRecord.setServiceClassCode(jTextFieldServiceClassCode.getText());
		achRecord.setCompanyName(jTextFieldCompanyName.getText());
		achRecord.setCompanyDiscretionaryData(jTextFieldCompanyDiscretionaryData.getText());
		achRecord.setCompanyId(jTextFieldCompanyIdentification.getText());
		achRecord.setStandardEntryClassCode(jTextFieldStandardEntryClassCode.getText());
		achRecord.setCompanyEntryDescription(jTextFieldCompanyEntryDescription.getText());
		achRecord.setCompanyDescriptiveDate(jTextFieldCompanyDescriptiveDate.getText());
		achRecord.setEffectiveEntryDate(jTextFieldEffectiveEntryDate.getText());
		achRecord.setSettlementDate(jTextFieldSettlementDate.getText());
		achRecord.setOriginatorStatusCode(jTextFieldOriginatorStatusCode.getText());
		achRecord.setOriginationDfiId(jTextFieldOriginatingDFIID.getText());
		achRecord.setBatchNumber(jTextFieldBatchNumber.getText());
	}

	/**
	 * @return the achRecord
	 */
	public synchronized ACHRecordBatchHeader getAchRecord() {
		return achRecord;
	}

	/**
	 * @param achRecord
	 *            the achRecord to set
	 */
	private synchronized void setAchRecord(ACHRecordBatchHeader achRecord) {
		this.achRecord = achRecord;
	}

	/**
	 * @return the buttonSelected
	 */
	public synchronized int getButtonSelected() {
		return buttonSelected;
	}

	/**
	 * @param buttonSelected
	 *            the buttonSelected to set
	 */
	public synchronized void setButtonSelected(int buttonSelected) {
		this.buttonSelected = buttonSelected;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelBatchHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRecordTypeCode = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldServiceClassCode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCompanyName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCompanyDiscretionaryData = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCompanyIdentification = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldStandardEntryClassCode = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldCompanyEntryDescription = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldCompanyDescriptiveDate = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldEffectiveEntryDate = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldSettlementDate = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldOriginatorStatusCode = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldOriginatingDFIID = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldBatchNumber = new javax.swing.JTextField();
        jPanelButtons = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ACH Batch Header");
        jLabel1.setText("Record Type: ");

        jTextFieldRecordTypeCode.setEditable(false);
        jTextFieldRecordTypeCode.setText("5");
        jTextFieldRecordTypeCode.setToolTipText("Must be 1");
        jTextFieldRecordTypeCode.setName("Record Type");

        jLabel12.setText("Service Class Code:");

        jTextFieldServiceClassCode.setText("123");
        jTextFieldServiceClassCode.setToolTipText("");
        jTextFieldServiceClassCode.setInputVerifier(new NumericVerifier(0,999));
        jTextFieldServiceClassCode.setName("Service Class Code");

        jLabel13.setText("Company Name:");

        jTextFieldCompanyName.setText("ABCDEFGHIJKLMNOP");
        jTextFieldCompanyName.setToolTipText("");
        jTextFieldCompanyName.setInputVerifier(new StringVerifier(1,16));
        jTextFieldCompanyName.setName("Company Name");

        jLabel14.setText("Company Discretionary Data:");

        jTextFieldCompanyDiscretionaryData.setText("ABCDEFGHIJKLMNOPQRST");
        jTextFieldCompanyDiscretionaryData.setToolTipText("");
        jTextFieldCompanyDiscretionaryData.setInputVerifier(new StringVerifier(0,20));
        jTextFieldCompanyDiscretionaryData.setName("Company Discretionary Data");

        jLabel15.setText("Company Identification:");

        jTextFieldCompanyIdentification.setText("ABCDEFGHIJ");
        jTextFieldCompanyIdentification.setToolTipText("");
        jTextFieldCompanyIdentification.setInputVerifier(new StringVerifier(1,10));
        jTextFieldCompanyIdentification.setName("Company Identification");

        jLabel16.setText("Standard Entry Class Code:");

        jTextFieldStandardEntryClassCode.setText("PPD");
        jTextFieldStandardEntryClassCode.setToolTipText("");
        jTextFieldStandardEntryClassCode.setInputVerifier(new StringVerifier(1,3));
        jTextFieldStandardEntryClassCode.setName("Standard Entry Class Code");

        jLabel17.setText("Company Entry Descr:");

        jTextFieldCompanyEntryDescription.setText("ABCDEFGHIJ");
        jTextFieldCompanyEntryDescription.setToolTipText("");
        jTextFieldCompanyEntryDescription.setInputVerifier(new StringVerifier(1,10));
        jTextFieldCompanyEntryDescription.setName("Company Entry Description");

        jLabel18.setText("Company Descriptive Date:");

        jTextFieldCompanyDescriptiveDate.setText("YYMMDD");
        jTextFieldCompanyDescriptiveDate.setToolTipText("");
        jTextFieldCompanyDescriptiveDate.setInputVerifier(new StringVerifier(0,6));
        jTextFieldCompanyDescriptiveDate.setName("Company Descriptive Date");

        jLabel19.setText("Effective Entry Date:");

        jTextFieldEffectiveEntryDate.setText("YYMMDD");
        jTextFieldEffectiveEntryDate.setToolTipText("");
        jTextFieldEffectiveEntryDate.setInputVerifier(new StringVerifier(6,6));
        jTextFieldEffectiveEntryDate.setName("Effective Entry Date");

        jLabel20.setText("Settlement Date(Julian):");

        jTextFieldSettlementDate.setText("999");
        jTextFieldSettlementDate.setToolTipText("");
        jTextFieldSettlementDate.setInputVerifier(new NumericVerifier(1,366));
        jTextFieldSettlementDate.setName("Settlement Date");

        jLabel21.setText("Originator Status Code:");

        jTextFieldOriginatorStatusCode.setText("X");
        jTextFieldOriginatorStatusCode.setToolTipText("");
        jTextFieldOriginatorStatusCode.setInputVerifier(new StringVerifier(1,1));
        jTextFieldOriginatorStatusCode.setName("Originator Status Code");

        jLabel22.setText("Originating DFI ID:");

        jTextFieldOriginatingDFIID.setText("TTTTAAAA");
        jTextFieldOriginatingDFIID.setToolTipText("");
        jTextFieldOriginatingDFIID.setInputVerifier(new StringVerifier(8,8));
        jTextFieldOriginatingDFIID.setName("Originating DFI Identification");

        jLabel23.setText("Batch Number:");

        jTextFieldBatchNumber.setText("1234567");
        jTextFieldBatchNumber.setToolTipText("");
        jTextFieldBatchNumber.setInputVerifier(new NumericVerifier(1,9999999L));
        jTextFieldBatchNumber.setName("Batch Number");

        javax.swing.GroupLayout jPanelBatchHeaderLayout = new javax.swing.GroupLayout(jPanelBatchHeader);
        jPanelBatchHeader.setLayout(jPanelBatchHeaderLayout);
        jPanelBatchHeaderLayout.setHorizontalGroup(
            jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBatchHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelBatchHeaderLayout.createSequentialGroup()
                            .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                            .addGap(6, 6, 6))
                        .addGroup(jPanelBatchHeaderLayout.createSequentialGroup()
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanelBatchHeaderLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBatchHeaderLayout.createSequentialGroup()
                        .addComponent(jTextFieldBatchNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelBatchHeaderLayout.createSequentialGroup()
                            .addComponent(jTextFieldOriginatingDFIID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(jPanelBatchHeaderLayout.createSequentialGroup()
                            .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldServiceClassCode, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(jTextFieldCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(jTextFieldCompanyDiscretionaryData, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(jTextFieldCompanyIdentification, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(jTextFieldStandardEntryClassCode, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(jTextFieldCompanyEntryDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(jTextFieldCompanyDescriptiveDate, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(jTextFieldEffectiveEntryDate, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(jTextFieldSettlementDate, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(jTextFieldOriginatorStatusCode, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldRecordTypeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(28, Short.MAX_VALUE)))))
        );
        jPanelBatchHeaderLayout.setVerticalGroup(
            jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBatchHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRecordTypeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldServiceClassCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldCompanyDiscretionaryData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCompanyIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStandardEntryClassCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCompanyEntryDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCompanyDescriptiveDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEffectiveEntryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldSettlementDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOriginatorStatusCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOriginatingDFIID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBatchNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonSave)
                .addComponent(jButtonCancel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelBatchHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBatchHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCancelActionPerformed
		dispose();
	}// GEN-LAST:event_jButtonCancelActionPerformed

	private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSaveActionPerformed
		retrieveDialogValues();
		setButtonSelected(SAVE_BUTTON);
		dispose();
	}// GEN-LAST:event_jButtonSaveActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ACHFileHeaderDialog(new javax.swing.JFrame(), true,
						new ACHRecordFileHeader()).setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanelBatchHeader;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JTextField jTextFieldBatchNumber;
    private javax.swing.JTextField jTextFieldCompanyDescriptiveDate;
    private javax.swing.JTextField jTextFieldCompanyDiscretionaryData;
    private javax.swing.JTextField jTextFieldCompanyEntryDescription;
    private javax.swing.JTextField jTextFieldCompanyIdentification;
    private javax.swing.JTextField jTextFieldCompanyName;
    private javax.swing.JTextField jTextFieldEffectiveEntryDate;
    private javax.swing.JTextField jTextFieldOriginatingDFIID;
    private javax.swing.JTextField jTextFieldOriginatorStatusCode;
    private javax.swing.JTextField jTextFieldRecordTypeCode;
    private javax.swing.JTextField jTextFieldServiceClassCode;
    private javax.swing.JTextField jTextFieldSettlementDate;
    private javax.swing.JTextField jTextFieldStandardEntryClassCode;
    // End of variables declaration//GEN-END:variables

}
