/*
 * ACHFileControlDialog.java
 *
 * Created on April 16, 2007, 7:45 PM
 */

package com.ach.achViewer;

import com.ach.achViewer.ach.ACHRecord;
import com.ach.achViewer.ach.ACHRecordEntryDetail;

/**
 * 
 * @author John
 */
public class ACHEntryDetailDialog extends ACHDialog {

	static final long serialVersionUID = 0;

	public static final int SAVE_BUTTON = 1;

	public static final int CANCEL_BUTTON = 2;

	private int buttonSelected = CANCEL_BUTTON;

	private ACHRecordEntryDetail achRecord = null;

	/** Creates new form ACHFileControlDialog */
	public ACHEntryDetailDialog(java.awt.Frame parent, boolean modal,
			ACHRecordEntryDetail achRecord) {
		super(parent, modal);
		initComponents();

		setAchRecord(achRecord);

		getRootPane().setDefaultButton(jButtonSave); // Sets the Save
		// button to default
		setLocationRelativeTo(null); // Centers the window on the screen
		loadDialogValues();
	}

	private void loadDialogValues() {
		jTextFieldRecordTypeCode.setText(String.valueOf(achRecord
				.getRecordTypeCode()));
		jComboBoxTransactionCode
				.setSelectedItem(achRecord.getTransactionCode());
		jTextFieldReceivingDFIID.setText(achRecord.getReceivingDfiId());
		jTextFieldCheckDigit.setText(achRecord.getCheckDigit());
		jTextFieldDFIAccountNbr.setText(achRecord.getDfiAcctNbr());
		jTextFieldAmount.setText(achRecord.getAmount());
		jTextFieldIndividualIDNumber.setText(achRecord.getIndividualIdNbr());
		jTextFieldIndividualName.setText(achRecord.getIndividualName());
		jTextFieldDiscretionaryData.setText(achRecord.getDiscretionaryData());
		jTextFieldAddendaRecordIndicator.setText(achRecord
				.getAddendaRecordInd());
		jTextFieldTraceNumber.setText(achRecord.getTraceNumber());
	}

	private void retrieveDialogValues() {
		achRecord.setRecordTypeCode(ACHRecord.ENTRY_DETAIL_TYPE);
		achRecord.setTransactionCode((String) jComboBoxTransactionCode
				.getSelectedItem());
		achRecord.setReceivingDfiId(jTextFieldReceivingDFIID.getText());
		achRecord.setCheckDigit(jTextFieldCheckDigit.getText());
		achRecord.setDfiAcctNbr(jTextFieldDFIAccountNbr.getText());
		achRecord.setAmount(jTextFieldAmount.getText());
		achRecord.setIndividualIdNbr(jTextFieldIndividualIDNumber.getText());
		achRecord.setIndividualName(jTextFieldIndividualName.getText());
		achRecord.setDiscretionaryData(jTextFieldDiscretionaryData.getText());
		achRecord.setAddendaRecordInd(jTextFieldAddendaRecordIndicator
				.getText());
		achRecord.setTraceNumber(jTextFieldTraceNumber.getText());
	}

	/**
	 * @return the achRecord
	 */
	public synchronized ACHRecordEntryDetail getAchRecord() {
		return achRecord;
	}

	/**
	 * @param achRecord
	 *            the achRecord to set
	 */
	private synchronized void setAchRecord(ACHRecordEntryDetail achRecord) {
		this.achRecord = achRecord;
	}

	/**
	 * @return the buttonSelected
	 */
	public synchronized int getButtonSelected() {
		return buttonSelected;
	}

	/**
	 * @param buttonSelected
	 *            the buttonSelected to set
	 */
	public synchronized void setButtonSelected(int buttonSelected) {
		this.buttonSelected = buttonSelected;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelBatchHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRecordTypeCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTransactionCode = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldReceivingDFIID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCheckDigit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDFIAccountNbr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIndividualIDNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldIndividualName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDiscretionaryData = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAddendaRecordIndicator = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTraceNumber = new javax.swing.JTextField();
        jPanelButtons = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("ACH Edit Detail");
        setModal(true);
        jLabel1.setText("Record Type: ");

        jTextFieldRecordTypeCode.setEditable(false);
        jTextFieldRecordTypeCode.setText("6");
        jTextFieldRecordTypeCode.setToolTipText("Must be 6");
        jTextFieldRecordTypeCode.setFocusable(false);
        jTextFieldRecordTypeCode.setName("Record Type");

        jLabel2.setText("Transaction Code:");

        jComboBoxTransactionCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "41", "42", "43", "44", "46", "47", "49", "51", "52", "53", "54", "55", "56", "81", "82", "83", "84", "85", "86" }));
        jComboBoxTransactionCode.setName("Transaction Code");

        jLabel3.setText("Receiving DFI ID:");

        jTextFieldReceivingDFIID.setText("12345678");
        jTextFieldReceivingDFIID.setToolTipText("");
        jTextFieldReceivingDFIID.setInputVerifier(new NumericVerifier(0,99999999L));
        jTextFieldReceivingDFIID.setName("Receiving DFI Identification");

        jLabel4.setText("Check Digit:");

        jTextFieldCheckDigit.setText("0");
        jTextFieldCheckDigit.setToolTipText("");
        jTextFieldCheckDigit.setInputVerifier(new NumericVerifier(0,9));
        jTextFieldCheckDigit.setName("Check Digit");

        jLabel5.setText("DFI Account ID:");

        jTextFieldDFIAccountNbr.setText("ABCDEFGHIJKLMNOPQRS");
        jTextFieldDFIAccountNbr.setToolTipText("");
        jTextFieldDFIAccountNbr.setInputVerifier(new StringVerifier(1,17));
        jTextFieldDFIAccountNbr.setName("DFI Account Number");

        jLabel6.setText("Amount:");

        jTextFieldAmount.setText("1234567890");
        jTextFieldAmount.setToolTipText("");
        jTextFieldAmount.setInputVerifier(new NumericVerifier(0,9999999999L));
        jTextFieldAmount.setName("Amount");

        jLabel7.setText("Individual ID Number:");

        jTextFieldIndividualIDNumber.setText("ABCDEFGHIJKLMNO");
        jTextFieldIndividualIDNumber.setToolTipText("");
        jTextFieldIndividualIDNumber.setInputVerifier(new StringVerifier(0,15));
        jTextFieldIndividualIDNumber.setName("Individual ID Number");

        jLabel8.setText("Individual Name:");

        jTextFieldIndividualName.setText("ABCDEFGHIJKLMNOPQRSTUV");
        jTextFieldIndividualName.setToolTipText("");
        jTextFieldIndividualName.setInputVerifier(new StringVerifier(1,22));
        jTextFieldIndividualName.setName("Individual Name");

        jLabel9.setText("Discretionary Data:");

        jTextFieldDiscretionaryData.setText("AB");
        jTextFieldDiscretionaryData.setToolTipText("");
        jTextFieldDiscretionaryData.setInputVerifier(new StringVerifier(0,2));
        jTextFieldDiscretionaryData.setName("Discretionary Data");

        jLabel10.setText("Addenda Record Indicator:");

        jTextFieldAddendaRecordIndicator.setText("0");
        jTextFieldAddendaRecordIndicator.setToolTipText("0=No addenda recs, 1=one or more addenda recs");
        jTextFieldAddendaRecordIndicator.setInputVerifier(new NumericVerifier(0,1));
        jTextFieldAddendaRecordIndicator.setName("Discretionary Data");

        jLabel11.setText("Trace Number:");

        jTextFieldTraceNumber.setText("123456789012345");
        jTextFieldTraceNumber.setToolTipText("");
        jTextFieldTraceNumber.setInputVerifier(new NumericVerifier(0,999999999999999L));
        jTextFieldTraceNumber.setName("Discretionary Data");

        javax.swing.GroupLayout jPanelBatchHeaderLayout = new javax.swing.GroupLayout(jPanelBatchHeader);
        jPanelBatchHeader.setLayout(jPanelBatchHeaderLayout);
        jPanelBatchHeaderLayout.setHorizontalGroup(
            jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBatchHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRecordTypeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTraceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddendaRecordIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDiscretionaryData, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIndividualName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIndividualIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDFIAccountNbr, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCheckDigit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldReceivingDFIID, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTransactionCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBatchHeaderLayout.setVerticalGroup(
            jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBatchHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRecordTypeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTransactionCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldReceivingDFIID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCheckDigit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDFIAccountNbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIndividualIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIndividualName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDiscretionaryData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddendaRecordIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBatchHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTraceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonSave)
                .addComponent(jButtonCancel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBatchHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBatchHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCancelActionPerformed
		dispose();
	}// GEN-LAST:event_jButtonCancelActionPerformed

	private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSaveActionPerformed
		retrieveDialogValues();
		setButtonSelected(SAVE_BUTTON);
		dispose();
	}// GEN-LAST:event_jButtonSaveActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ACHEntryDetailDialog(new javax.swing.JFrame(), true,
						new ACHRecordEntryDetail()).setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxTransactionCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelBatchHeader;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JTextField jTextFieldAddendaRecordIndicator;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldCheckDigit;
    private javax.swing.JTextField jTextFieldDFIAccountNbr;
    private javax.swing.JTextField jTextFieldDiscretionaryData;
    private javax.swing.JTextField jTextFieldIndividualIDNumber;
    private javax.swing.JTextField jTextFieldIndividualName;
    private javax.swing.JTextField jTextFieldReceivingDFIID;
    private javax.swing.JTextField jTextFieldRecordTypeCode;
    private javax.swing.JTextField jTextFieldTraceNumber;
    // End of variables declaration//GEN-END:variables

}
