/*
 * ACHFileControlDialog.java
 *
 * Created on April 16, 2007, 7:45 PM
 */

package com.ach.achViewer;

import com.ach.achViewer.ach.ACHRecord;
import com.ach.achViewer.ach.ACHRecordFileControl;

/**
 * 
 * @author John
 */
public class ACHFileControlDialog extends ACHDialog {

	static final long serialVersionUID = 0;

	public static final int SAVE_BUTTON = 1;

	public static final int CANCEL_BUTTON = 2;

	private int buttonSelected = CANCEL_BUTTON;

	private ACHRecordFileControl achRecord = null;

	/** Creates new form ACHFileControlDialog */
	public ACHFileControlDialog(java.awt.Frame parent, boolean modal,
			ACHRecordFileControl achRecord) {
		super(parent, modal);
		initComponents();

		setAchRecord(achRecord);

		getRootPane().setDefaultButton(jButtonSave); // Sets the Save
		// button to default
		setLocationRelativeTo(null); // Centers the window on the screen
		loadDialogValues();
	}

	private void loadDialogValues() {
		jTextFieldRecordTypeCode.setText(String.valueOf(achRecord
				.getRecordTypeCode()));
		jTextFieldBatchCount.setText(achRecord.getBatchCount());
		jTextFieldBlockCount.setText(achRecord.getBlockCount());
		jTextFieldEntryAddendaCount.setText(achRecord.getEntryAddendaCount());
		jTextFieldEntryHash.setText(achRecord.getEntryHash());
		jTextFieldDebitDollarAmount.setText(achRecord.getTotDebitDollarAmt());
		jTextFieldCreditDollarAmount.setText(achRecord.getTotCreditDollarAmt());
		jTextFieldReserved.setText(achRecord.getReserved());
	}

	private void retrieveDialogValues() {
		achRecord.setRecordTypeCode(ACHRecord.FILE_CONTROL_TYPE);
		achRecord.setBatchCount(jTextFieldBatchCount.getText());
		achRecord.setBlockCount(jTextFieldBlockCount.getText());
		achRecord.setEntryAddendaCount(jTextFieldEntryAddendaCount.getText());
		achRecord.setEntryHash(jTextFieldEntryHash.getText());
		achRecord.setTotDebitDollarAmt(jTextFieldDebitDollarAmount.getText());
		achRecord.setTotCreditDollarAmt(jTextFieldCreditDollarAmount.getText());
		achRecord.setReserved(jTextFieldReserved.getText());
	}

	/**
	 * @return the achRecord
	 */
	public synchronized ACHRecordFileControl getAchRecord() {
		return achRecord;
	}

	/**
	 * @param achRecord
	 *            the achRecord to set
	 */
	private synchronized void setAchRecord(ACHRecordFileControl achRecord) {
		this.achRecord = achRecord;
	}

	/**
	 * @return the buttonSelected
	 */
	public synchronized int getButtonSelected() {
		return buttonSelected;
	}

	/**
	 * @param buttonSelected
	 *            the buttonSelected to set
	 */
	public synchronized void setButtonSelected(int buttonSelected) {
		this.buttonSelected = buttonSelected;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelFileControl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRecordTypeCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBatchCount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBlockCount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEntryAddendaCount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEntryHash = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDebitDollarAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCreditDollarAmount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldReserved = new javax.swing.JTextField();
        jPanelButtons = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ACH File Control");
        jLabel1.setText("Record Type: ");

        jTextFieldRecordTypeCode.setEditable(false);
        jTextFieldRecordTypeCode.setText("9");
        jTextFieldRecordTypeCode.setFocusable(false);
        jTextFieldRecordTypeCode.setName("Record Type");

        jLabel2.setText("Batch Count:");

        jTextFieldBatchCount.setText("123456");
        jTextFieldBatchCount.setInputVerifier(new NumericVerifier(0,999999));
        jTextFieldBatchCount.setName("Batch Count");

        jLabel3.setText("Block Count:");

        jTextFieldBlockCount.setText("123456");
        jTextFieldBlockCount.setInputVerifier(new NumericVerifier(0,999999));
        jTextFieldBlockCount.setName("Block Count");

        jLabel4.setText("Entry/Addenda Count:");

        jTextFieldEntryAddendaCount.setText("12345678");
        jTextFieldEntryAddendaCount.setInputVerifier(new NumericVerifier(0,99999999));
        jTextFieldEntryAddendaCount.setName("Entry/Addenda Count");

        jLabel5.setText("Entry Hash:");

        jTextFieldEntryHash.setText("1234567890");
        jTextFieldEntryHash.setInputVerifier(new NumericVerifier(0,9999999999L));
        jTextFieldEntryHash.setName("Entry Hash");

        jLabel6.setText("Total Debit Entry:");

        jTextFieldDebitDollarAmount.setText("123456789012");
        jTextFieldDebitDollarAmount.setInputVerifier(new NumericVerifier(0,999999999999L));
        jTextFieldDebitDollarAmount.setName("Total Debit Entry");

        jLabel7.setText("Total Credit Entry:");

        jTextFieldCreditDollarAmount.setText("123456789012");
        jTextFieldCreditDollarAmount.setInputVerifier(new NumericVerifier(0,999999999999L));
        jTextFieldCreditDollarAmount.setName("Total Credit Entry");

        jLabel8.setText("Reserved:");

        jTextFieldReserved.setEditable(false);
        jTextFieldReserved.setText(" ");
        jTextFieldReserved.setFocusable(false);
        jTextFieldReserved.setInputVerifier(new StringVerifier(0,39));
        jTextFieldReserved.setName("Reserved");

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonSave)
                .addComponent(jButtonCancel))
        );

        javax.swing.GroupLayout jPanelFileControlLayout = new javax.swing.GroupLayout(jPanelFileControl);
        jPanelFileControl.setLayout(jPanelFileControlLayout);
        jPanelFileControlLayout.setHorizontalGroup(
            jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFileControlLayout.createSequentialGroup()
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFileControlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldReserved, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCreditDollarAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDebitDollarAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jTextFieldEntryHash, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jTextFieldEntryAddendaCount, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jTextFieldBlockCount, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jTextFieldBatchCount, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jTextFieldRecordTypeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(jPanelFileControlLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelFileControlLayout.setVerticalGroup(
            jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFileControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRecordTypeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldBatchCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldBlockCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEntryAddendaCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEntryHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDebitDollarAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCreditDollarAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldReserved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFileControl, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFileControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCancelActionPerformed
		dispose();
	}// GEN-LAST:event_jButtonCancelActionPerformed

	private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSaveActionPerformed
		retrieveDialogValues();
		setButtonSelected(SAVE_BUTTON);
		dispose();
	}// GEN-LAST:event_jButtonSaveActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ACHFileControlDialog(new javax.swing.JFrame(), true,
						new ACHRecordFileControl()).setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelFileControl;
    private javax.swing.JTextField jTextFieldBatchCount;
    private javax.swing.JTextField jTextFieldBlockCount;
    private javax.swing.JTextField jTextFieldCreditDollarAmount;
    private javax.swing.JTextField jTextFieldDebitDollarAmount;
    private javax.swing.JTextField jTextFieldEntryAddendaCount;
    private javax.swing.JTextField jTextFieldEntryHash;
    private javax.swing.JTextField jTextFieldRecordTypeCode;
    private javax.swing.JTextField jTextFieldReserved;
    // End of variables declaration//GEN-END:variables

}
